name: my 3rd assignment using aws cic/cd pipeline
on:
  push:
    branches: [main]

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and save results
        run: npm run check | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

  deployJob:
    runs-on: ubuntu-latest
    needs: testJob
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: artifacts

      - name: Display test results
        run: cat artifacts/test-results.txt || true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install PM2
        run: npm install -g pm2

      - name: Start application
        run: pm2 start "./src/server.js" --name node-app

      - name: PM2 Save
        run: pm2 save